---
- name: validate required connection is configured
  fail:
    msg: "expected connection value to be set to network_cli, got {{ ansible_connection }}"
  when: ansible_connection != 'network_cli'

- name: validate enable mode is configured
  fail:
    msg: "ansible_become must be set to True"
  when: ansible_become is undefined or not ansible_become

- name: validate become method is set to enable
  fail:
    msg: "ansible_become_method must be set to enable to work with eos"
  when: ansible_become_method != 'enable'

- name: run command and return configuration
  cli:
    command: "{{ eos_config_source[source | default('running')] }}"
  register: configuration

- name: set the configuration fact
  set_fact:
    configuration: "{{ configuration.stdout }}"
